ElasticNet:
  alpha: 0.3
  l1_ratio: 0.1

#เป็นค่าควบคุมความแรงของการ regularization ถ้า alpha มากแสดงว่าการควบคุมความซับซ้อนของโมเดลจะเข้มงวดมากขึ้น
#ค่าน้อย: โมเดลจะซับซ้อนมากขึ้นและอาจเกิด overfitting ได้ง่าย
#ค่ามาก: โมเดลจะถูก regularized มากขึ้น ทำให้ลดโอกาสการเกิด overfitting แต่ความแม่นยำอาจลดลง

#เป็นค่าที่บอกว่าเราจะใช้ L1 regularization (Lasso) เทียบกับ L2 regularization (Ridge) ในสัดส่วนเท่าไหร่
#ค่าน้อย (ใกล้ 0): โมเดลจะใช้ L2 regularization เป็นหลัก
#ค่าสูง (ใกล้ 1): โมเดลจะใช้ L1 regularization เป็นหลัก
 
#Ridge จะลดค่าตัวแปรให้เล็กลง แต่ไม่ทำให้เป็นศูนย์
#Lasso จะตัดตัวแปรที่ไม่สำคัญออกไปเลย

#r2
#ค่าสูง (ใกล้ 1): โมเดลสามารถอธิบายความแปรปรวนของข้อมูลได้ดีมาก
#ค่าต่ำ (ใกล้ 0 หรือ ติดลบ): โมเดลอธิบายความแปรปรวนได้น้อยหรือไม่ดี